### PR TITLE
Update balance-competing-priorities.md

### PR DESCRIPTION
**Pull request by john-par**
Updates related to [User Story 1703303](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1703303).

### CODE REVIEW

**Comment by PRMerger10** [comment]
@john-par : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by john-par** [comment]
This PR is a minor change for a LOC fix.

#sign-off

**Comment by PRMerger12** [comment]
@john-par: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Looks good; merging.

@John-par Would you please work in the private repo? An edit like this would be auto-merged, which is ideal. 👍

**Pull request merged**
