### PR TITLE
Update security-governance-and-compliance.md

### PR DESCRIPTION
**Pull request by nielsophey**
add "," to have a unified typo

### CODE REVIEW

**Comment by PRMerger6** [comment]
@nielsophey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I'll leave this open for @BrianBlanchard to review, but it looks like "security" modifies "governance and compliance"; that is, it's an article about the governance and compliance of security. So, no comma would appear to be correct.

**Comment by BrianBlanchard** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @BrianBlanchard - Adding a comma, per the PR, introduces an inconsistency and ambiguity in meaning:


image


Does the phrase refer to three items, _security, governance, and compliance_, or does it refer to governance and compliance as it relates to security (_security governance and compliance_)? In either case, adding a single comma, as the PR does, wouldn't appear to be correct . . .

**Pull request merged**
