### PR TITLE
Update management-group-and-subscription-organization.md

### PR DESCRIPTION
**Pull request by pazdedav**
Updated two design recommendations for MG organization, added references (links) to articles describing how to protect MG hierarchy

### CODE REVIEW

**Comment by PRMerger14** [comment]
@pazdedav : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrianBlanchard** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
