### PR TITLE
Akasnik migrate tailwind update diagrams

### PR DESCRIPTION
**Pull request by akasnik**
EMEA FastTrack doc-a-thon - Updated diagrams to match newest discovery features.

### CODE REVIEW

**Comment by Court72** [comment]
@alejandra8481 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by alejandra8481 — CHANGES_REQUESTED** [review]
Looks great! A small request though before approving, on the discovery-workflow.png, remove "See link D" under box: "Enable dependency mapping and app discovery...."

**Comment by alejandra8481** [comment]
Perfect. Looks great. #sign-off

**Comment by PRMerger18** [comment]
@alejandra8481: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Court72** [comment]
Trying #sign-off again

**Comment by PRMerger8** [comment]
@Court72: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by akasnik** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@akasnik: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ShannonLeavitt** [comment]
Thanks for your sign-offs @akasnik and @alejandra8481 ; In a new PR, consider making these additional improvements to the images:

* Standardize all instances of "VMWare" and "Vmware" with this capitalization: "VMware", per the Microsoft Cloud style guide.
* Standardize all instances of "Hyper-v" with this capitalization: "Hyper-V".
* Standardize all instances of "Vcenter" with this capitalization: "vCenter".

**Pull request merged**
