### PR TITLE
Update purview-deployment.md

### PR DESCRIPTION
**Pull request by zeinab-mk**
updated Azure Purview roles

### CODE REVIEW

**Comment by PRMerger8** [comment]
@zeinab-mk : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zeinam

**Comment by jborsecnik** [comment]
@zeinab-mk, are you a Microsoft employee? The article shows "zeinam" as the author AND ms.author

If so, you should work in the private repo. And you should link your Microsoft and GitHub aliases, as described in the Contributors Guide, and update the ms.author fields to your Microsoft alias.

**Comment by Jak-MS** [comment]
@zeinab-mk - a recent sync with the private repo has caused some PRs to develop merge conflicts. Can you check with the live site to make sure these updaters are still needed. If so, you'll need to resolve the merge conflicts in this PR, or close it and open a new one.  If they're not need please just close the PR. 

Thanks.

**Comment by ShannonLeavitt** [comment]
This article no longer exists in the repo. I'll close the PR now.

**Pull request closed without merging**
