### PR TITLE
Contoso Migration Series Updates

### PR DESCRIPTION
**Pull request by deltadan**
- Broad updates to move guidance for migrations away from Azure Site Recovery to Azure Migrate.
- Delete Service Fabric Guidance docs
- Remove references to Cloudyn
- Add new doc for Refactor Windows to App Services and MI

### CODE REVIEW

**Comment by tfosmark** [comment]
@JanetCThomas Can you review this large set of changes? Given the scope of changes, if these are acceptable the commits should be moved to the private repo for full validation.

Thank you!

**Comment by deltadan** [comment]
FYI - @alexbuckgit is helping with this PR.

**Comment by ktoliver** [comment]
@deltadan Using a branch name other than "master" might help with this PR. Example, do the work in a working branch called "patch-1" or any term or phrase rather than "master" or "live".

**Comment by deltadan** [comment]
> @deltadan Using a branch name other than "master" might help with this PR. Example, do the work in a working branch called "patch-1" or any term or phrase rather than "master" or "live".

do you want me to close this PR and open a new one from a branch?

**Comment by ktoliver** [comment]
> > @deltadan Using a branch name other than "master" might help with this PR. Example, do the work in a working branch called "patch-1" or any term or phrase rather than "master" or "live".
> 
> do you want me to close this PR and open a new one from a branch?

Yes, that would be helpful. Thanks!

**Comment by deltadan** [comment]
replacing this PR with one from a branch.

**Pull request closed without merging**
