### PR TITLE
Add missing hypens in abbreviation name

### PR DESCRIPTION
**Pull request by DenisBalan**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@DenisBalan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@BrianBlanchard 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by jamasten** [comment]
Not all of these resource types support hyphens.  Each suggestion needs to be validated.  For instance, "Microsoft.ContainerRegistry/registries" only supports alphanumeric characters and should not have a hyphen.

**Comment by ShannonLeavitt** [comment]
These changes are now reflected in the [live article](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations). I'll close this PR now. Thanks.

**Pull request closed without merging**
