### PR TITLE
added 'why' to several ES network design recs

### PR DESCRIPTION
**Pull request by jknightly**
this was intended for the initial release but PR never merged.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@jknightly : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrianBlanchard** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi, the [Microsoft Writing Style Guide](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36389) says, "Use contractions." So, I made that change here, FYI. Thanks!

**Pull request merged**
