### PR TITLE
Proposing abbreviation for MariaDB

### PR DESCRIPTION
**Pull request by SvenAelterman**

### CODE REVIEW

**Comment by AnnaMHuff** [comment]
@BrianBlanchard - Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Thanks!

#label:"aq-pr-triaged"

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

@MicrosoftDocs/public-repo-pr-review-team

**Comment by ShannonLeavitt** [comment]
#assign: @martinekuan
#unassign: @BrianBlanchard

**Comment by ShannonLeavitt** [comment]
#unassign: @BrianBlanchard

**Comment by stephen-sumner** [comment]
@SvenAelterman - Thank you so much for your feedback. So sorry for the delay. This is great input that we'll take into consideration. 

I'm collecting a number of abbreviation suggestions from customers and going to create a separate PR to update them all at once. So, I'm going to close this PR without merging. 

Thank you so much for feedback. It's greatly appreciated!

**Pull request closed without merging**
