### PR TITLE
Fix title in step #3

### PR DESCRIPTION
**Pull request by akasnik**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@akasnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@WendyRing : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WendyRing** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@WendyRing: I'm sorry - only the author of this article, @alejandra8481, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
