### PR TITLE
Typo "Azure files service"→"Azure Files service"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-network-topology-and-connectivity https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/eslz-network-topology-and-connectivity.md #PingMSFTDocs

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[c904dd2](https://github.com/hyoshioka0128/cloud-adoption-framework/commits/c904dd2671d9bfd5a071a4680cad72f1b4d28dd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/wvd/eslz-network-topology-and-connectivity.md](https://github.com/hyoshioka0128/cloud-adoption-framework/blob/patch-6/docs/scenarios/wvd/eslz-network-topology-and-connectivity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209181521497117-951/BuildReport?accessString=8e74f19203984a3d774d5f14fe44367d292ebad046cc61eb68397231571df787).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Court72** [comment]
@danycontre

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by hyoshioka0128** [comment]
#sign-off

**Comment by American-Dipper** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off. 

 

#label:"aq-pr-triaged" 

#label:"pending-content-team/business-approval" 

Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
#label:"cact-review-in-progress"

**Comment by BryanLa** [comment]
CACT #sign-off
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Pull request merged**
