### PR TITLE
Update eslz-management-and-monitoring.md

### PR DESCRIPTION
**Pull request by ianwhytez**
Add link to /azure/azure-vmware/send-logs-to-log-analytics per Varun Hariharan

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[268fd8d](https://github.com/ianwhytez/cloud-adoption-framework/commits/268fd8d0baeae00c2ded0193b1cc378e7e0ffc12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/azure-vmware/eslz-management-and-monitoring.md](https://github.com/ianwhytez/cloud-adoption-framework/blob/add-link-to-log-analytics/docs/scenarios/azure-vmware/eslz-management-and-monitoring.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202211221721098986-1007/BuildReport?accessString=5ef05e1f0e9b54d09b34d696f8f457c8421d0b77423a241e4b7cad666f06606d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@prasad3017 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ianwhytez** [comment]
@Court72 it looks like your comment was directed at @prasad3017, but it brings to my attention the fact that I haven't signed off on this PR. Actually, I was expecting to be able to create the PR in Draft mode so I could verify that the link works, but if I had that opportunity, I missed it. 

So (1) Do you want me to sign off on the PE and (2) is there a preview link for it?

For the record, I'm making this change at the request of Varun Hariharan,

**Comment by Court72** [comment]
Hi @ianwhytez 

Thanks for your questions! Note that this PR was opened in the *public repo*, where there's no staging available and the listed author must sign off on PRs that make changes to their article. 

Do you want to close this PR and open it in the [private repo](https://github.com/MicrosoftDocs/azure-docs-pr) instead?

**Comment by ianwhytez** [comment]
Ah, I see. I overlooked that detail when I forked the repo. Just to be clear - I need to fork the private repo before I can open the PR there, true?

**Comment by ianwhytez** [comment]
Well I've got the forking (and cloning) part down. Just need to fork the right repo %-)

**Pull request closed without merging**
