### PR TITLE
Adding diagrams to holistically visualize App delivery

### PR DESCRIPTION
**Pull request by azureflipper**
Often my customers are asking for a visualization which contains all of the application delivery guidelines in one or two drawings. I created two diagrams showing the recommended and considered ingress and egress traffic patterns as described in the Plan for App Delivery segment of ALZ.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@azureflipper : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by azureflipper** [comment]
Maybe these diagrams also make sense to commit to: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-inbound-and-outbound-internet-connectivity.

**Comment by PRMerger18** [comment]
@azureflipper : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@azureflipper : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by azureflipper** [comment]
Have I missed anything?

**Comment by ktoliver** [comment]
@BrianBlanchard @JanetCThomas could you take a look at the proposed update? Thanks.

**Pull request closed without merging**
