### PR TITLE
Update alerting.md

### PR DESCRIPTION
**Pull request by danterasera**
Adding explanation that Service Health alerts are configured through Azure Service Health instead of Azure Monitor to avoid user confusion. @MGoedtel

### CODE REVIEW

**Comment by PRMerger10** [comment]
@danterasera : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@MGoedtel, I removed the "en-us". Ok to merge? Thanks.

**Comment by PRMerger8** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved the merge conflict. Merging the PR.

**Pull request merged**
