### PR TITLE
change names to Azure landing zones

### PR DESCRIPTION
**Pull request by mosabami**
Change enterprise scale to Azure landing zones

### CODE REVIEW

**Comment by PRMerger5** [comment]
@mosabami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@mosabami: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mosabami** [comment]
@BrianBlanchard @JanetCThomas @WendyRing

**Comment by JanetCThomas** [comment]
@mosabami - landing zone accelerator should always be lower case.  Can you please make this correction?

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger9** [comment]
@mosabami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
#sign-off  -  this has been reviewed and approved by the content team.

**Comment by PRMerger7** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
