### PR TITLE
Update naming-and-tagging.md

### PR DESCRIPTION
**Pull request by jpmicrosoft**
Network Examples had incorrect examples under Route table.
Route table	Resource group	route-<route table name>	
lb-navigator-prod-001
lb-sharepoint-dev-001

### CODE REVIEW

**Comment by PRMerger15** [comment]
@jpmicrosoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by alexbuckgit** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@alexbuckgit: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by BrianBlanchard** [comment]
#sign-off

**Pull request merged**
