### PR TITLE
Update enable.md

### PR DESCRIPTION
**Pull request by KarenYin01**
Removed layout metadata, updated ms.topic and updated cards to bullet lists. Refer to https://dev.azure.com/ceapex/Engineering/_boards/board/t/Content%20Eng/Stories/?workitem=210488.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@KarenYin01 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
@KarenYin01 This topic it being replaced with our May release. Content is very fluid at the moment. Please hold off on this type of changes until after our May release to help us avoid conflicts with our release branch merges.  For future updates that change the layout of a page, please us the private repo so that we can preview your changes.  Thank you!

**Comment by ktoliver** [comment]
@JanetCThomas @KarenYin01 If the article will be replaced or substantially updated, merge conflicts in this PR are likely. So, we'll close this PR. If it's preferable to keep the PR open for future consideration, please do reopen it. Thanks.

**Comment by KarenYin01** [comment]
@JanetCThomas @ktoliver Got it. Thank you for the comments. 👍

**Comment by KarenYin01** [comment]
@JanetCThomas @ktoliver Sorry for the inconvenience. Submitted the PR to private repo. No need to reopen this PR. Thank you. :-)
PR Link: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/487.

**Pull request closed without merging**
