### PR TITLE
Replaced "resource prefix" guidance

### PR DESCRIPTION
**Pull request by LeeSchuenemeyer**
Based on real world application of these best practices, using resource naming conventions that suggest a resource name prefix to identify the resource type creates problems immediately.   It eliminates the ability to sort the resource alphabetically to find the resource by its unique name.  Resource Types should be used as a suffix.  This creates a the ranking of resource name meta data from "most unique" to "least unique".   "Unique Resource Name"-"Resource Number"-"Resource Location"-"Resource Type" creates a resource name that can be sorted alphabetically, and identifies the resource by the most unique part of the name first.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@LeeSchuenemeyer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jlorich** [comment]
I strongly agree with this premise.  You can already sort by resource type in the portal.  Using a prefix of resource type completely eliminates the ability to sort by name.

**Comment by BrianBlanchard** [comment]
Lee, thanks for the PR. Joey, thanks for adding perspective & meeting in person today.

Putting this PR on hold for a moment. Internally, we don’t have a great “why” behind prefix vs postfix. There are a number of internal conversations about this topic. If you’re interested I’d like to pull you both into a think tank to discuss “why”, commit to a decision, & then update the article. If you’re interested, ping me offline & pull you in.

Thanks again for your contributions!

**Comment by BrianBlanchard** [comment]
Closing per prior comment. Once a decision is reached, we will need to rework these edits to get past the merge conflicts, which will require a new PR.

**Pull request closed without merging**
