### PR TITLE
Correct link for 'Operating model terminology'

### PR DESCRIPTION
**Pull request by skabou**
Correct link for 'Operating model terminology'
Regarding issue: #828

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[c435d29](https://github.com/MicrosoftDocs/cloud-adoption-framework/commits/c435d290598857450259d4d4af5ee22803efae7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/operating-model/compare.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/skabou-patch-1/docs/operating-model/compare.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202210121529419259-969/BuildReport?accessString=94b84e757fe6464c0a51f93a84cf30a0584fe6e6cd20fb6f15221ed229889620).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by jborsecnik** [comment]
@BrianBlanchard, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by hallihan — APPROVED** [review]
Looks good, :shipit:

**Comment by skabou** [comment]
#sign-off

**Pull request merged**
