### PR TITLE
fixed inaccuracies in some of the sentences. added image of golden state

### PR DESCRIPTION
**Pull request by mosabami**
Fixed some inaccuracies in some parts of the documentation and added picture of the golden state. 

Ayobami Ayodeji

### CODE REVIEW

**Comment by PRMerger9** [comment]
@mosabami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@BrianBlanchard Could you review the proposed update to your article? I see some blocking items to fix before merging, so the commit should be submitted in the private repo. PMs usually work in the private repo, but we can help by moving the commit to the private repo. Thanks.

**Comment by mosabami** [comment]
@ktoliver what are some of the blocking items? also can you send a link to the private repo?

**Comment by mosabami** [comment]
> @BrianBlanchard Could you review the proposed update to your article? I see some blocking items to fix before merging, so the commit should be submitted in the private repo. PMs usually work in the private repo, but we can help by moving the commit to the private repo. Thanks.

@ktoliver what are some of the blocking items? also can you send a link to the private repo?

**Comment by ktoliver** [comment]
> > @BrianBlanchard
> >             
> >             Brian Blanchard (AZURE PNP)
> >             FTE Could you review the proposed update to your article? I see some blocking items to fix before merging, so the commit should be submitted in the private repo. PMs usually work in the private repo, but we can help by moving the commit to the private repo. Thanks.
> 
> @ktoliver Kristine Toliver (Aquent LLC) Vendor what are some of the blocking items? also can you send a link to the private repo?

@mosabami Hi, I'll send you an email that has the information. It will include a link to the specific quality criteria that are applied in the private repo, such as that file names can contain only lowercase letters, numbers, and hyphens, including in the file extension. I'll send email shortly. Thanks.

**Comment by ktoliver** [comment]
Email sent. Thanks.

**Comment by PRMerger8** [comment]
@mosabami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mosabami** [comment]
Merging into the pr repo instead.

**Pull request closed without merging**
