### PR TITLE
URL not displaying properly

### PR DESCRIPTION
**Pull request by thommck**
corrected the syntax

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[eb3e80a](https://github.com/thommck/cloud-adoption-framework/commits/eb3e80abda56ce809ee93707078c962dc00676b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/considerations/devops-toolchain.md](https://github.com/thommck/cloud-adoption-framework/blob/patch-1/docs/ready/considerations/devops-toolchain.md) | :warning:Warning | | [Details](#user-content-48d409d0bf0c071fe062f5a4bf3b2e2f-6171b7fe)

<a id="48d409d0bf0c071fe062f5a4bf3b2e2f-6171b7fe"></a>
### [docs/ready/considerations/devops-toolchain.md](https://github.com/thommck/cloud-adoption-framework/blob/patch-1/docs/ready/considerations/devops-toolchain.md)
 - **Line 24, Column 200**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#full-stack-Azure-DevOps-toolchain' in 'ready/considerations/devops-toolchain.md', did you mean '#full-stack-azure-devops-toolchain'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202301041225533572-1044/BuildReport?accessString=b0e7c9366aa9f0066e29916886c671456fc40cd047b3b60390a4ecc43b94a09b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[ded2c02](https://github.com/thommck/cloud-adoption-framework/commits/ded2c02566679af8a9831a1aa795a560e685d3df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/considerations/devops-toolchain.md](https://github.com/thommck/cloud-adoption-framework/blob/patch-1/docs/ready/considerations/devops-toolchain.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202301041417110251-1044/BuildReport?accessString=3787a0d44233d2252c34b23eaff1e4e745b97696ffb0b912e799d97be54e57cf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by ckittel — APPROVED** [review]
LGTM

**Comment by ckittel** [comment]
CACT #sign-off

**Pull request merged**
