### PR TITLE
Update organize-resources.md

### PR DESCRIPTION
**Pull request by wayneme75**
added a link for creating subscriptions programmatically.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@wayneme75 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @laraaleite

**Comment by ktoliver** [comment]
@doodlemania2 - Could you review this pull request?

If it's approved, the update needs to be edited (assuming no other changes are requested) to:

\<line break\>
\> \[\!NOTE\]\
\> Subscriptions also can be created programmatically. \[Learn more\]\(https\:\/\/docs.microsoft.com/azure/azure-resource-manager/management/programmatically-create-subscription?tabs=azure-powershell)

**Comment by doodlemania2** [comment]
@ktoliver - for items in the CAF repo, please bring in @alexbuckgit

**Comment by ktoliver** [comment]
> @ktoliver - for items in the CAF repo, please bring in @alexbuckgit

Got it. Thanks!

**Comment by PRMerger17** [comment]
@alexbuckgit : Thanks for your contribution! The author(s) have been notified to review your proposed change. @laraaleite

**Pull request merged**
