### PR TITLE
Update traditional-azure-networking-topology.md

### PR DESCRIPTION
**Pull request by dimilider**
VPN-Gateway can have up to 100 S2S Connections.

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[bf2649d](https://github.com/dimilider/cloud-adoption-framework/commits/bf2649dc759f2260d0d222103410b209954ec3d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/traditional-azure-networking-topology.md](https://github.com/dimilider/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/traditional-azure-networking-topology.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209210833085801-953/BuildReport?accessString=dbf080cfbb332df2ae0bc446e8e3b2534ba26d7e0fa29b3b012938177cab64cc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by sitarant — CHANGES_REQUESTED** [review]
@dimilider, thanks for submitting this update, can you pls specify only Gen2 VpnGw4, VpnGw4 AZ and VpnGw5 and VpnGw5 AZ as not all the Vpn Gateway supports 100 tunnels

**Comment by Jak-MS** [comment]
@sitarant 
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by American-Dipper** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off. 

 

#label:"aq-pr-triaged" 

#label:"pending-content-team/business-approval" 

Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
#label:"cact-review-in-progress"

**Comment by BryanLa** [comment]
CACT #sign-off

**Pull request merged**
