### PR TITLE
Add Microsoft.Network/privateEndpoints

### PR DESCRIPTION
**Pull request by JayDoubleu**
~~- Add Microsoft.Network/privateEndpoints~~
- Fix typos

#sign-off

### CODE REVIEW

**Comment by PRMerger4** [comment]
@JayDoubleu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@BrianBlanchard - Could you take a look at the proposed changes?

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ckittel** [comment]
CACT #sign-off

**Comment by JayDoubleu** [comment]
#sign-off

**Pull request merged**
