### PR TITLE
Azure Charts links added

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**
As discussed with Abdul Sheik

### CODE REVIEW

**Comment by PRMerger16** [comment]
@AlekseiPolkovnikov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@AlekseiPolkovnikov Would you make the updates as requested by @jelledruyts? Thanks!

**Comment by PRMerger8** [comment]
@AlekseiPolkovnikov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AlekseiPolkovnikov** [comment]
Review notes reflected

**Pull request merged**
