### PR TITLE
FIxing a few typos

### PR DESCRIPTION
**Pull request by Tbohunek**
Also would be nice to
- [ ] add links to all mentioned policies

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Tbohunek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Tbohunek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Tbohunek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
This issue has been triaged by the CAF team and can be merged.  The changes suggested are approved.  #sign-off

**Comment by PRMerger7** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @JefferyMitchell, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by JefferyMitchell — APPROVED** [review]

**Pull request merged**
