### PR TITLE
Added new AVS BCDR flowchart and updated the content

### PR DESCRIPTION
**Pull request by sonmitt**
Added the new BCDR and HA decision chart having information about latest features. 
Added partner solutions - Jetstream and Zerto
Added Stretch cluster
Removed Azure Site Recovery 
Removed old content which is not relevant.  
Updated overall BCDR guidance

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[edb6693](https://github.com/sonmitt/cloud-adoption-framework/commits/edb6693a24130fdcd867e01a8878a0444b70d89e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md) | :warning:Warning | | [Details](#user-content-6565e9b0fc423236aca7e91880b5a905-ee8fc666)
[docs/scenarios/_images/eslz-bcdr-1.3.png](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.3.png) | :white_check_mark:Succeeded | |
[docs/scenarios/_images/eslz-bcdr-1.3.svg](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.3.svg) | :white_check_mark:Succeeded | |

<a id="6565e9b0fc423236aca7e91880b5a905-ee8fc666"></a>
### [docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'mhenry, sonmitt' is not a valid GitHub ID.`````
 - **Line 30, Column 513**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-vsan-stretched-clusters' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 97, Column 36**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-disaster-recovery-using-jetstream' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 97, Column 147**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-zerto-disaster-recovery#scenario-3-azure-vmware-solution-to-iaas-vms-cloud-disaster-recovery' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 99, Column 7**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-zerto-disaster-recovery#scenario-3-azure-vmware-solution-to-iaas-vms-cloud-disaster-recovery' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 103, Column 26**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209271755455761-959/BuildReport?accessString=8630722dfe53262bfd50c6d7f03fb1d0fd57a2826f26fb09ff48cdbb88218448).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jborsecnik** [comment]
@janetCThomas, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[faa69ce](https://github.com/sonmitt/cloud-adoption-framework/commits/faa69cebecaddac58a5dd90930521108ad01340f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md) | :warning:Warning | | [Details](#user-content-6565e9b0fc423236aca7e91880b5a905-8b49e53c)
[docs/scenarios/_images/eslz-bcdr-1.3.png](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.3.png) | :white_check_mark:Succeeded | |
[docs/scenarios/_images/eslz-bcdr-1.3.svg](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.3.svg) | :white_check_mark:Succeeded | |

<a id="6565e9b0fc423236aca7e91880b5a905-8b49e53c"></a>
### [docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'mhenry,sonmitt' is not a valid GitHub ID.`````
 - **Line 30, Column 513**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/azure-vmware/deploy-vsan-stretched-clusters'.`````
 - **Line 97, Column 36**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-disaster-recovery-using-jetstream' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 97, Column 147**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-zerto-disaster-recovery#scenario-3-azure-vmware-solution-to-iaas-vms-cloud-disaster-recovery' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 99, Column 7**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-zerto-disaster-recovery#scenario-3-azure-vmware-solution-to-iaas-vms-cloud-disaster-recovery' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 103, Column 26**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 97, Column 36**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-disaster-recovery-using-jetstream' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 97, Column 147**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-zerto-disaster-recovery#scenario-3-azure-vmware-solution-to-iaas-vms-cloud-disaster-recovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 99, Column 7**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/azure/azure-vmware/deploy-zerto-disaster-recovery#scenario-3-azure-vmware-solution-to-iaas-vms-cloud-disaster-recovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 103, Column 26**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209301742116881-959/BuildReport?accessString=aa57b6ee10a88c284939413b31e5b178c74e48c16f263f29cad2c801a7cf37dc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by JanetCThomas** [comment]
@jborsecnik @sonmitt - this needs to be moved to the private repo.  DO NOT MERGE.

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[b59b12c](https://github.com/sonmitt/cloud-adoption-framework/commits/b59b12c9ab826385957a6dd4e620ff82b4b59967)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md) | :warning:Warning | | [Details](#user-content-6565e9b0fc423236aca7e91880b5a905-74afaa20)
[docs/scenarios/azure-vmware/previous-bcdr.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/previous-bcdr.md) | :warning:Warning | | [Details](#user-content-c45cdbf60628a336d70f294dc87f6ccf-74afaa20)
[docs/scenarios/_images/eslz-bcdr-1.2.png](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.2.png) | :white_check_mark:Succeeded | |
[docs/scenarios/_images/eslz-bcdr-1.2.svg](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.2.svg) | :white_check_mark:Succeeded | |
[docs/scenarios/_images/eslz-bcdr-1.3.png](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.3.png) | :white_check_mark:Succeeded | |
[docs/scenarios/_images/eslz-bcdr-1.3.svg](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.3.svg) | :white_check_mark:Succeeded | |

<a id="6565e9b0fc423236aca7e91880b5a905-74afaa20"></a>
### [docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Enterprise-scale BCDR for Azure VMware Solution - Cloud Adoption Framework' is duplicated in: 'scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md(2,8), scenarios/azure-vmware/previous-bcdr.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'mhenry,sonmitt' is not a valid GitHub ID.`````
 - **Line 13, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Business continuity and disaster recovery (BCDR) for Azure VMware Solution enterprise-scale scenario' is duplicated with other articles: 'scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md(13,1), scenarios/azure-vmware/previous-bcdr.md(13,1)'. First level headings must be unique within a docset.`````
 - **Line 33, Column 513**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/azure-vmware/deploy-vsan-stretched-clusters'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how this enterprise-scale scenario can improve business continuity and disaster recovery (BCDR) of Azure VMware Solution.' is duplicated in 'scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md(3,14)', 'scenarios/azure-vmware/previous-bcdr.md(3,14)'.`````

<a id="c45cdbf60628a336d70f294dc87f6ccf-74afaa20"></a>
### [docs/scenarios/azure-vmware/previous-bcdr.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/previous-bcdr.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Enterprise-scale BCDR for Azure VMware Solution - Cloud Adoption Framework' is duplicated in: 'scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md(2,8), scenarios/azure-vmware/previous-bcdr.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 13, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Business continuity and disaster recovery (BCDR) for Azure VMware Solution enterprise-scale scenario' is duplicated with other articles: 'scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md(13,1), scenarios/azure-vmware/previous-bcdr.md(13,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn how this enterprise-scale scenario can improve business continuity and disaster recovery (BCDR) of Azure VMware Solution.' is duplicated in 'scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md(3,14)', 'scenarios/azure-vmware/previous-bcdr.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209301858090006-959/BuildReport?accessString=f8627c9efb781574ebfa57eb8e446de77955c0c974a526e5d5af0ce7964cc948).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[d4701d3](https://github.com/sonmitt/cloud-adoption-framework/commits/d4701d36915ba30e62bcbfd0b0cda280375435f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md) | :warning:Warning | | [Details](#user-content-6565e9b0fc423236aca7e91880b5a905-d317406d)
[docs/scenarios/_images/eslz-bcdr-1.2.png](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.2.png) | :white_check_mark:Succeeded | |
[docs/scenarios/_images/eslz-bcdr-1.2.svg](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/_images/eslz-bcdr-1.2.svg) | :white_check_mark:Succeeded | |

<a id="6565e9b0fc423236aca7e91880b5a905-d317406d"></a>
### [docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/sonmitt/cloud-adoption-framework/blob/eslz-bcdr-updates/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'mhenry,sonmitt' is not a valid GitHub ID.`````
 - **Line 33, Column 513**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/azure-vmware/deploy-vsan-stretched-clusters'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209301910439093-959/BuildReport?accessString=4676db03a711de55c4012f86e011e690079564cb39fe4fa01e0d770eee23c35c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Pull request closed without merging**
