### PR TITLE
Update contoso-migration-refactor-web-app-sql-managed-instance.md

### PR DESCRIPTION
**Pull request by dellis2121**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@dellis2121 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @givenscj

**Comment by ktoliver** [comment]
Hi @BrianBlanchard - Could you review this PR? The changes look similar to those made in https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/280. Thanks.

**Comment by JanetCThomas** [comment]
These changes are fine.  Just need to remove the en-us from the URLs before we merge to master.

**Comment by JanetCThomas** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @givenscj, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
