### PR TITLE
Update of the bulleting

### PR DESCRIPTION
**Pull request by baba2k18**
Processes was shown as a seperate Heading, which can confuse the reader as it is part of the Corporate policies and should be a bullet instead of a Heading.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@baba2k18 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

@MicrosoftDocs/public-repo-pr-review-team

#assign: @martinekuan
#unassign: @BrianBlanchard

**Review by ckittel — CHANGES_REQUESTED** [review]
Processes is not part of "Coporate Policies"  The image above clearly has it as after and this is a dedicated H3 for the purpose.  I'm going to request this PR be closed.

**Comment by ckittel** [comment]
#please-close

**Comment by ckittel** [comment]
On second thought, I'm totally wrong about that.  Reopening.

**Review by ckittel — APPROVED** [review]
Thanks!

**Comment by ckittel** [comment]
CACT #sign-off

**Comment by BryanLa** [comment]
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Pull request merged**
