### PR TITLE
Proximity Placement Groups prefix

### PR DESCRIPTION
**Pull request by RyanLWilliams**
Added Proximity Placement Groups prefix

### CODE REVIEW

**Comment by PRMerger17** [comment]
@RyanLWilliams : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RyanLWilliams** [comment]
This is still awaiting review :)

**Comment by RyanLWilliams** [comment]
@BrianBlanchard still awaiting your review?

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

**Note:** In the suggested content, the hyphen might need to be deleted from the abbreviation.

@MicrosoftDocs/public-repo-pr-review-team

#assign: @martinekuan
#unassign: @BrianBlanchard

**Comment by ckittel** [comment]
Looks like you and @SvenAelterman had the same idea, great! I'm going to close this as a duplicate of #620.

#please-close

**Pull request closed without merging**
