### PR TITLE
Update storage-options.md

### PR DESCRIPTION
**Pull request by arntdg**
#sign-off

### CODE REVIEW

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add #sign-off in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"

**Comment by PRMerger14** [comment]
@Jak-MS: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by BrianBlanchard** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@BrianBlanchard, the last sentence added doesn't show in preview, so apparently it's malformed. Does this belong in the same cell, as a new paragraph (rather than a new row).  Can you fix, tell me how it should appear, or bring this over to the private repo for staging and validation? Thanks.  

image

**Comment by jborsecnik** [comment]
#hold-off

**Comment by arntdg** [comment]
Apologies, I think I have missed the cell termination sign ( | ) at the end of the sentence in question. I can't seem to make this change now though. How do I reopen the file for edit?

**Comment by jborsecnik** [comment]
> Apologies, I think I have missed the cell termination sign ( | ) at the end of the sentence in question. I can't seem to make this change now though. How do I reopen the file for edit?

No problem. Is this how it should look? In the same cell, but as a separate paragraph?

image

**Comment by PRMerger7** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
#hold-off

**Comment by arntdg** [comment]
@jborsecnik Yes, that is what it should look like. Thanks. Please proceed.

**Comment by arntdg** [comment]
#sign-off

**Comment by PRMerger12** [comment]
### :warning: PRMerger: You can’t sign off on draft PR 

- You signed off, but this PR is a draft and can’t be merged. If you’re ready for this PR to be reviewed, select <b>Ready for review</b> toward the bottom of the PR, then sign off again.

**Comment by PRMerger15** [comment]
@arntdg: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jborsecnik** [comment]
@BrianBlanchard, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

**Comment by arntdg** [comment]
@jborsecnik Kindly revisit this update request and sign off and merge. TIA!

**Pull request merged**
