### PR TITLE
Update resource-naming.md

### PR DESCRIPTION
**Pull request by tikicoder**
updating so that vm includes the dash as part of the naming.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@tikicoder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by tikicoder** [comment]
is this waiting for me to sign off on anything, just want to make sure I am not the reason it is inactive.

**Comment by jborsecnik** [comment]
> is this waiting for me to sign off on anything, just want to make sure I am not the reason it is inactive.

It needs author approval for merge. @BrianBlanchard, can you review this PR? Thanks.

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

@MicrosoftDocs/public-repo-pr-review-team

#assign: @martinekuan
#unassign: @BrianBlanchard

**Review by ckittel — APPROVED** [review]
LGTM, this isn't a service that requires no `-` in the names, so it makes sense to apply the delinators like the rest.

@stephen-sumner -- okay to accept?

**Comment by stephen-sumner** [comment]
#sign-off

**Comment by stephen-sumner** [comment]
@ckittel - Looks good! I don't have permission to sign off

cc: @ShannonLeavitt @jborsecnik @BryanLa

**Comment by BryanLa** [comment]
> @ckittel Chad Kittel FTE - Looks good! I don't have permission to sign off
> 
> cc: @ShannonLeavitt Shannon Leavitt (Aquent LLC) Vendor @jborsecnik @BryanLa Bryan Lamos FTE

Thanks @stephen-sumner! Guidance will be coming via email today on public repo PR sign-off, but it's essentially:

CACT #sign-off
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Comment by ckittel** [comment]
CACT #sign-off

**Comment by stephen-sumner** [comment]
@BryanLa - Thank you!

**Pull request merged**
