### PR TITLE
Update eslz-business-continuity-and-disaster-recovery.md

### PR DESCRIPTION
**Pull request by MayDay47**
Adjusted the statements on use of Availability zones to the current state of AVD.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@MayDay47 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@igorpag 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
#label: keep-open

**Comment by Jak-MS** [comment]
@igorpag - nudge.

**Comment by ckittel** [comment]
Hey there Claus, there has been a change to this file since you proposed this.  Can you please merge the changes and if this is still needed we can move forward.

@MayDay47

**Comment by American-Dipper** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
	
#label:"aq-pr-triaged"
#label:"pending-content-team/business-approval"
Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
> @MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
> 
> #label:"aq-pr-triaged" #label:"pending-content-team/business-approval" Cc: @MicrosoftDocs/public-repo-pr-review-team

@American-Dipper - just a heads up that ckittel (in CACT) has done initial review on this one and is waiting for a response from the contributor (see [above](https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/922#issuecomment-1464507158))

#label:"cact-review-in-progress"

**Comment by American-Dipper** [comment]
> > @MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
> > #label:"aq-pr-triaged" #label:"pending-content-team/business-approval" Cc: @MicrosoftDocs/public-repo-pr-review-team
> 
> @American-Dipper Jeff Borsecnik (Aquent LLC) Vendor - just a heads up that ckittel (in CACT) has done initial review on this one and is waiting for a response from the contributor (see [above](https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/922#issuecomment-1464507158))
> 
> #label:"cact-review-in-progress"

Thanks. Yah, I was sort of following the letter of a new procedure, which is awkward in this case.  -jb

**Comment by igorpag** [comment]
Hi all, don't know why I lost the notification of this, sorry for that. Anyway, due to a recent change in AVD, the additional content added in the PR is not correct anymore and then should be not merged. Now during AVD pool deployment you can select all the zones you want, not necessary to repeat the procedure for each AZ. Can we close this PR? Thanks.

**Comment by ckittel** [comment]
#please-close

Thanks @igorpag

**Pull request closed without merging**
