### PR TITLE
Update Broken Links on Policy definition.

### PR DESCRIPTION
**Pull request by JefferyMitchell**
Update Broken Links on Policy definition. 
Deploy-Diag-ActivityLog
Deploy-Diag-LogAnalytics
Deploy-VM-Monitoring

### CODE REVIEW

**Comment by PRMerger12** [comment]
@JefferyMitchell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
