### PR TITLE
AKS - Checklist

### PR DESCRIPTION
**Pull request by whereisyusuf**
Updated sections for Plan, train and Proof - specifically around network design and availability

### CODE REVIEW

**Comment by PRMerger8** [comment]
@whereisyusuf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@sabbour It looks like some of the revisions in the PR might have been made to master (hence the merge conflict), but not all of them. Is the PR still in review?  Thanks.

**Comment by PRMerger18** [comment]
@alexbuckgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@alexbuckgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@alexbuckgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by alexbuckgit — APPROVED** [review]

**Comment by alexbuckgit** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@alexbuckgit: I'm sorry - only the author of this article, @sabbour, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
