### PR TITLE
Update small fix on wording.md

### PR DESCRIPTION
**Pull request by bsantacruzms**
Fixing wording as AzHOP is not a service in Azure.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@Rajani-Janaki-Ram 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Rajani-Janaki-Ram** [comment]
@Brian ***@***.***>,

Please edit the sentence from "Azure Batch and Azure HPC OnDemand Platform (AzHop) are hosted in Microsoft Azure that have different functions and capabilities."

TO
Azure Batch and Azure Cycle Cloud are both Azure provided 1st party service while Azure HPC OnDemand Platform (AzHop) is an automation built on top of Azure Cloud which delivers an end-2-end deployment mechanism for a complete HPC cluster solution in Azure.

Thanks,
Rajani.

**Comment by American-Dipper** [comment]
@Rajani-Janaki-Ram - please sign off is this is ok to merge.

**Comment by bsantacruzms** [comment]
--signoff

**Comment by bsantacruzms** [comment]
@Rajani-Janaki-Ram This is the PR waiting to merge.

**Comment by Rajani-Janaki-Ram** [comment]
#sign-off

**Pull request merged**
