### PR TITLE
Moodle migration documentation update

### PR DESCRIPTION
**Pull request by UmakanthOS**
+ Updated general language, Linux commands
- Removed vpn-gateway.md and references to that document, added a redirected to deal with any accesses to this resource

### CODE REVIEW

**Comment by PRMerger8** [comment]
@UmakanthOS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @UmakanthOS - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

The internal contributor guide describes how to move a commit from the public repo to the private repo.

**Comment by JanetCThomas** [comment]
Hi @UmakanthOS - we will take care of moving this to the private repo.  Thanks!

**Comment by v-thepet** [comment]
Moved to PR https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/1169.

**Pull request closed without merging**
