### PR TITLE
Update design-guidelines.md

### PR DESCRIPTION
**Pull request by nielsophey**
just a typo error - "," to much

### CODE REVIEW

**Comment by PRMerger16** [comment]
@nielsophey : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @nielsophey - [Microsoft style](https://docs.microsoft.com/style-guide/punctuation/commas) is to use serial commas:

image

We'll close the PR. Thank you!

**Comment by ktoliver** [comment]
Actually, looking at the article, the issue is that "security" modifies "governance and compliance," so there should be no comma. I'll make that edit and merge the PR.

**Comment by ktoliver** [comment]
I can't edit the PR so I'll do it in a separate PR.

**Pull request closed without merging**
