### PR TITLE
Zeinam purview updates1

### PR DESCRIPTION
**Pull request by zeinab-mk**
updated purview best practices based on purview recent changes

### CODE REVIEW

**Comment by PRMerger7** [comment]
@zeinab-mk : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zeinam

**Comment by zeinab-mk** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@zeinab-mk: I'm sorry - only the author of this article, @zeinam, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @zeinab-mk - This pull request was opened in the public repo. Authors should make updates to their published articles in the private repo. Would you create a pull request in the private repo for this content update? Thank you! We'll close this PR.

**Pull request closed without merging**
