### PR TITLE
request for SQL Server on Azure VM

### PR DESCRIPTION
**Pull request by ingebeumer**
Hi team,
Would it be possible to add a recommended abbreviation for SQL Server on Azure VM to better distinguish database servers in between all other VM? | SQL Server on Azure VM | `Microsoft.Compute/virtualMachines` | `sqlvm-` | sqlvm- would be in line with sql- for Azure SQL Database server and sqlmi- for Azure SQL Managed Instance.  Thx for reviewing. 
Kind regards, Inge

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[838560c](https://github.com/ingebeumer/cloud-adoption-framework/commits/838560c944d73bcb4090eac9d52a28d28117cf73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/ingebeumer/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202209171503303856-950/BuildReport?accessString=c92ca087b006eb1dbe2df3aa4d99f50b33556aea7763da5d7c8264e3ae44f2bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ingebeumer** [comment]
sign-off

**Comment by ingebeumer** [comment]
#sign-off

**Comment by ckittel** [comment]
@stephen-sumner - this PR is a request to add another naming convention. Can you weigh on this decision?

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[e6b10b9](https://github.com/ingebeumer/cloud-adoption-framework/commits/e6b10b9544a614bec1a8d976202c668cc9e34194)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/ingebeumer/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202301042020150077-950/BuildReport?accessString=194b49349793d4fe7fe4d8c445be8d993484ecb17285bc764f548d173a32b331).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by stephen-sumner** [comment]
@ckittel - looking at it now. Thanks!

**Comment by stephen-sumner** [comment]
@ingebeumer - Thank you so much for the suggestion!  I thought about it a bit. Since this is technically just another VM, I think it's better not recommend abbreviations for the images/software running on the VM for the global audience. 

However, at the end of the day, your naming conventions should work for you and your organization. I can see value in using that abbreviation in your environment. Great thought!

Thank you again!

**Comment by ingebeumer** [comment]
Thank you for your considerations @stephen-sumner, I'll include it in future conversations with our customers.

**Pull request closed without merging**
