### PR TITLE
Update transition.md

### PR DESCRIPTION
**Pull request by mbilalamjad**
Victor Azrate and I discussed linking this article to other relevant articles which provide guidance on moving subscriptions and resources to complete the story for our customers. Please let us know your feedback if this looks good to publish.

I have added the below to existing line#34
"For more guidance on how to move subscriptions between management groups in the same tenant please refer to this [article](/azure/governance/management-groups/manage#move-subscriptions)."

I have added the below to a new line#64
"For more guidance on how to move resources between resources groups and subscriptions in the same tenant please refer to this [article](/azure/azure-resource-manager/management/move-resource-group-and-subscription). In case you plan on deploying Enterprise-Scale in a new region and moving resources from the original region where they are deployed at the moment then use [Azure Resource Mover](/azure/resource-mover/overview) service for this use case."

### CODE REVIEW

**Comment by PRMerger20** [comment]
@mbilalamjad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mbilalamjad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mbilalamjad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@JanetCThomas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
#sign-off - okay to merge these changes.

**Comment by PRMerger17** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @JefferyMitchell, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
