### PR TITLE
Adding Container Apps Environment

### PR DESCRIPTION
**Pull request by agoncal**
A Container App needs to be in a container apps environment. I tend to name them with `ctae`. What do you think?

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[57002fc](https://github.com/agoncal/cloud-adoption-framework/commits/57002fc306d86a5a7e5d441f16536aeae1bcf728)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/agoncal/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202210281330281505-984/BuildReport?accessString=19c752e93bf7adc3ca1c44059a405e30199d8fbd1775282302e2e3887c07c930).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@stephen-sumner 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[d9047c2](https://github.com/agoncal/cloud-adoption-framework/commits/d9047c289729d24dc71b74f45288eb67d882e792)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/agoncal/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202210281618200326-984/BuildReport?accessString=4feed925ca58c095ba0b30b483f28ae0eae21a0e9b414e8e640c6b940a2b1ae1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by stephen-sumner** [comment]
@agoncal and @sinedied - Thanks so much for the feedback and input! I always want this to meet customer needs. 

I just pushed a commit to update the namespace based on this page: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-bicep

I liked both, but ultimately aligned to Yohan's suggestion since Antonio gave it a thumbs up.

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[87a1e8e](https://github.com/agoncal/cloud-adoption-framework/commits/87a1e8e8fe8308dc393a5ef1eadbd5797337a759)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/agoncal/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202210281624511803-984/BuildReport?accessString=4b1616799b0abc59babbf5bfe7ca33b87399cea010615e93bcd5fe12aeca5713).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by stephen-sumner — APPROVED** [review]
I made some updates and liked the improvements.

**Comment by stephen-sumner** [comment]
#sign-off

**Pull request merged**
