### PR TITLE
rodrigosantosms-updating-ALZ-diagram-pictures

### PR DESCRIPTION
**Pull request by rodrigosantosms**
rodrigosantosms-updating-ALZ-diagram-pictures

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[2a2cdb0](https://github.com/rodrigosantosms/cloud-adoption-framework/commits/2a2cdb0b912c86de68e5bee8bb7cf17d80ed495a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/enterprise-scale/media/ns-arch-cust.png](https://github.com/rodrigosantosms/cloud-adoption-framework/blob/Rosanto-Main/docs/ready/enterprise-scale/media/ns-arch-cust.png) | :white_check_mark:Succeeded | |
[docs/ready/enterprise-scale/media/ns-arch-cust-expanded.png](https://github.com/rodrigosantosms/cloud-adoption-framework/blob/Rosanto-Main/docs/ready/enterprise-scale/media/ns-arch-cust-expanded.png) | :white_check_mark:Succeeded | |
[docs/ready/enterprise-scale/media/ns-arch-cust-inline.png](https://github.com/rodrigosantosms/cloud-adoption-framework/blob/Rosanto-Main/docs/ready/enterprise-scale/media/ns-arch-cust-inline.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202210262042034276-983/BuildReport?accessString=6410150a11c3d3d863a9bf3d457db9bdc078196dae93f43f5e5ec18c6849960b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by jborsecnik** [comment]
@rodrigosantosms, what articles are these images uses in? We need to identify the author for approval. Thanks.

**Comment by Court72** [comment]
@WendyRing 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by mSarts** [comment]
Closed due to duplicate work item that already merged - https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3994.

**Pull request closed without merging**
