### PR TITLE
update template - project details

### PR DESCRIPTION
**Pull request by wayneme75**
Adding Microsoft Project to the management of the ADO.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@wayneme75 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
