### PR TITLE
BrokenLinkBugs: Fix broken bookmark from 3/9/20 CATS Test

### PR DESCRIPTION
**Pull request by v-thepet**
Per User Story https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1596864/?triage=true.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-thepet : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-thepet** [comment]
No build?

**Comment by v-thepet** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@v-thepet: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by v-thepet** [comment]
wrong repo

**Pull request closed without merging**
