### PR TITLE
Add abbreviation for API Connections

### PR DESCRIPTION
**Pull request by Devvox93**
Docs change only.
An abbreviation for API Connections was missing in the docs. The proposed abbreviation is clear and does not collide with an existing abbreviation.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Devvox93 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@BrianBlanchard 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Devvox93** [comment]
#sign-off

I'm not sure if the sign-off note was to me or to Brian, but nothing happened in 2 weeks, so I assume it was to me :)

**Comment by PRMerger17** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @BrianBlanchard

**Comment by Jak-MS** [comment]
@Devvox93 - sorry, but @BrianBlanchard will need to review and sign off before we can merge this. thanks!

@BrianBlanchard - can you take a look?

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[9c6155b](https://github.com/Devvox93/cloud-adoption-framework/commits/9c6155bb840f8e64f74c1bfcdcd98afaa156348c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/Devvox93/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202211011118108952-923/BuildReport?accessString=f1841d08f0d5ea9f3612527b6ddfddbcede5fbac5321a33f138e6fe0889f4318).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[2561446](https://github.com/Devvox93/cloud-adoption-framework/commits/256144679d0920d96c09d554ccda8d6c13233ff6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/Devvox93/cloud-adoption-framework/blob/patch-1/docs/ready/azure-best-practices/resource-abbreviations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202211011140346958-923/BuildReport?accessString=eb76e6fa8ded247e1d28ad623578f69890e32d54f6d044911d6726d70a0840f0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by stephen-sumner** [comment]
@Devvox93 - Thank you for the input! I really appreciate the time it took to provide the suggestion. 

Just a quick question. Are these APIs for Logic Apps?

**Comment by Devvox93** [comment]
@stephen-sumner Yes indeed. API Connections for Logic Apps, that's why I added them under "Integration".

**Comment by Devvox93** [comment]
@stephen-sumner Do you need more input from me, besides your question I answered earlier?

**Comment by stephen-sumner** [comment]
@Devvox93 - I apologize for the delay. We try to be as comprehensive as possible in our abbreviations without digging too far into the child resources. At this time, we can't include this recommendation, though it's a good one. The name space is deep and has a location variable. For example, "Microsoft.Web/locations/<your-region>/managedApis/<your api connection>. This is deeper than most abbreviations on this page and for some built-in triggers/actions the name of the API connection has a default that isn't configurable. I hope you understand. It's a great suggestion but just not right for this page I'm afraid. Thank you so much for your time, and please let us know if you have any other suggestions.

**Pull request closed without merging**
