### PR TITLE
Azure Synapse Analytics Dedicated SQL Pool

### PR DESCRIPTION
**Pull request by ZMon3y**
Replaced Azure SQL Data Warehouse with Azure Synapse Analytics Dedicated SQL Pool to align with the current nomenclature.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ZMon3y : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@brianblanchard

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by jborsecnik** [comment]
@BrianBlanchard

Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a #sign-off comment to signal that the PR is ready for the review team to merge.

**Comment by ShannonLeavitt** [comment]
This article has been [largely updated](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/data-options) since this PR was submitted, and the changes no longer apply. I'll close this PR. Thank you for your contribution.

**Pull request closed without merging**
