### PR TITLE
NAT for VPN Gateway is GA

### PR DESCRIPTION
**Pull request by chetanv-code**
NAT for VPN Gateway is GA, removing the preview keyword from the doc. pls see https://azure.microsoft.com/en-in/updates/vpn-nat-now-ga/

### CODE REVIEW

**Comment by PRMerger15** [comment]
@chetanv-code : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Review by JefferyMitchell — APPROVED** [review]

**Comment by JefferyMitchell** [comment]
@sitarant can you take a look at this update?

**Comment by sitarant** [comment]
> @sitarant can you take a look at this update?

@JefferyMitchell it looks good to me

**Comment by JefferyMitchell** [comment]
@sitarant Thank you #sign-off

**Pull request merged**
