### PR TITLE
Update eslz-network-topology-connectivity.md

### PR DESCRIPTION
**Pull request by dmauser**
1) Remove Azure Route Server Note because it is already in GA. See announcement: https://azure.microsoft.com/en-us/updates/azure-route-server-ga/
2) Azure Route Server allows ExpressRoute and VPN transit in the same way Azure Virtual WAN does. See reference: https://docs.microsoft.com/en-us/azure/route-server/expressroute-vpn-support

### CODE REVIEW

**Comment by PRMerger10** [comment]
@dmauser : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
	
#label:"aq-pr-triaged"
#label:"pending-content-team/business-approval"
Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
**CACT Review notes:** this PR was originally filed to remove the `[!NOTE] Azure Route Server is currently in public preview.` alert. A PR reviewer later updated the contributor's branch with a commit that obviated the contributor's original ask (since the NOTE alert had been removed in the interim). The replaced section now appears as:
image


Closing this as "already fixed".

**Pull request closed without merging**
