### PR TITLE
Typo "Postgres"→"PostgreSQL"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-postgresql-to-azure
https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/contoso-migration-postgresql-to-azure.md
#PingMSFTDocs

### CODE REVIEW

**Comment by PRMerger9** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @deltadan

**Comment by hyoshioka0128** [comment]
#sign-off

**Comment by American-Dipper** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
	
#label:"aq-pr-triaged"
#label:"pending-content-team/business-approval"
Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
#label:"cact-review-in-progress"

**Comment by BryanLa** [comment]
CACT #sign-off
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Pull request merged**
