### PR TITLE
Enterprise-scale review by Janet

### PR DESCRIPTION
**Pull request by JanetCThomas**
Review by Janet

### CODE REVIEW

**Comment by PRMerger8** [comment]
@JanetCThomas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@JanetCThomas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @JanetCThomas A review of this scope should be done in the private repository to take advantage of automated validations, Acrolinx, staging, and PR review. Would you transfer your updates to a pull request in the private repo? Alternatively, the PR review team can move the commit to the private repo and create a new PR for the author to review. Which would you like to do?

(All contributors who work in the Product Manager role should open pull requests in the private repository for advanced quality validations and staging. To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL.)

Thanks.

cc @tfosmark

**Comment by JanetCThomas** [comment]
I didn't realize I did this in the public repo.  Yes, can the PR review team move the commit to the private repo and create a new PR for review?  I'm not sure how to do it.   Thanks!

**Comment by ktoliver** [comment]
> I didn't realize I did this in the public repo. Yes, can the PR review team move the commit to the private repo and create a new PR for review? I'm not sure how to do it. Thanks!

@JanetCThomas Yes! We'll do it early this afternoon. I'll assign the PR to @BrianBlanchard, and cc you in the PR (the PR will be opened by me, in my fork, but you will be the contributor on record). Thanks. 👍

**Comment by ktoliver** [comment]
Moved to private repository: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/657

We'll close this PR now. Thanks.

**Comment by ktoliver** [comment]
@JanetCThomas FYI, here are the steps to [Pull public commits to the private repo for updates, staging, publication](https://review.docs.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=master#pull-public-commits-to-the-private-repo-for-updates-staging-publication), in case you ever need it.

**Pull request closed without merging**
