### PR TITLE
Update contoso-migration-rds-to-wvd.md

### PR DESCRIPTION
**Pull request by tkcdcdcb**
The option of command Convert-RoamingProfile is wrong.

Wrong : -MaxVHDSize
Correct : -VHDMaxSizeGB

The command might be sourced from the web (preview command??)
https://christiaanbrinkhoff.com/2020/02/14/youtube-how-to-migrate-from-upd-to-fslogix-profile-container-profiles-to-windows-virtual-desktop/

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[082b0c4](https://github.com/tkcdcdcb/cloud-adoption-framework/commits/082b0c48c1aa732924a14173d0886c60223a19f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md](https://github.com/tkcdcdcb/cloud-adoption-framework/blob/patch-1/docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202212050750184838-1019/BuildReport?accessString=882167eaa95367f6e54f7c14102e602cd8a971d26b30a198d30d4c145bfdac53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@stephen-sumner

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by stephen-sumner** [comment]
@Court72  - I'm getting a second opinion on this one.

**Comment by hallihan** [comment]
@stephen-sumner This looks correct based on the commands in the downloaded preview Powershell module

**Review by stephen-sumner — APPROVED** [review]

**Comment by stephen-sumner** [comment]
@Court72 - I signed off, but don't have permission in public repo. We don't need betnstegink to review this. I can create a PR in the private repo if you can merge either.

**Review by benstegink — APPROVED** [review]

**Review by stephen-sumner — COMMENTED** [review]
I'm closing and doing this on the private repo side.

**Comment by stephen-sumner** [comment]
@tkcdcdcb - Thank you for your input and catching this! You'll see this update in the next day or so. Thanks so much!

**Pull request closed without merging**
