### PR TITLE
Update enterprise-scale-landing-zone.md

### PR DESCRIPTION
**Pull request by MayDay47**
Updated Naming to Azure Virtual Desktop

### CODE REVIEW

**Comment by PRMerger19** [comment]
@MayDay47 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@MayDay47 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@MayDay47 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@BrianBlanchard Would you be able to review the terminology update for all the articles?

**Comment by PRMerger19** [comment]
@alexbuckgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
