### PR TITLE
Update resource-abbreviations.md

### PR DESCRIPTION
**Pull request by sandroasp**
add option abbreviations and new ones

### CODE REVIEW

**Comment by PRMerger4** [comment]
@sandroasp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@BrianBlanchard - Could you take a look at the proposed changes?

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

@MicrosoftDocs/public-repo-pr-review-team

#assign:@martinekuan
#unassign:@BrianBlanchard

**Comment by ckittel** [comment]
We will likely not be adding optional abbreviation examples.  If you'd like to open a new PR for any ones that you added that we haven't already added, please do so.

#please-close

**Pull request closed without merging**
