### PR TITLE
Wording was off

### PR DESCRIPTION
**Pull request by JFolberth**
Staffed by "four" teams.  There isn't a definition of what these teams are...also felt odd to have an arbitrary number so guessing this was a typo.  I believe the sentiment is something like multiple teams. Feel free to correct.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@JFolberth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger14** [comment]
@JFolberth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JFolberth** [comment]
@BrianBlanchard, cleaning up old PRs and giving this a bump.

**Comment by JFolberth** [comment]
@ktoliver  @JanetCThomas  Closing up some old PRs and checking on this one.

**Comment by ktoliver** [comment]
Hi @JFolberth. I'm not a SME, so I can't provide approval in this instance.

@JanetCThomas Could you take a look at the proposed change? 

Thanks!

**Comment by JanetCThomas** [comment]
#sign-off

**Pull request merged**
