### PR TITLE
Suggesting abbreviation for proximity placement groups

### PR DESCRIPTION
**Pull request by SvenAelterman**
Suggesting `ppg` as the abbreviation for proximity placement groups.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@SvenAelterman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

**Note:**  The hyphens might need to be removed from the suggested content.

@MicrosoftDocs/public-repo-pr-review-team

#assign: @martinekuan
#unassign: @BrianBlanchard

**Comment by stephen-sumner** [comment]
@SvenAelterman -  Thank you so much for your feedback. So sorry for the delay. This is great input that we'll take into consideration. 

I'm collecting a number of abbreviation suggestions from customers, and I'm going to create a separate PR to update them all at once. So, I'm going to close this PR without merging but will incorporate your feedback.

Thank you so much for feedback. It's greatly appreciated!

**Pull request closed without merging**
