### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by KittyChiu**
Business continuity is a key driver for many business as we experience in this pandemic.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@kichiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@BrianBlanchard @JanetCThomas - Could you review the proposed update? I made a few small edits, in the event that it's approved.

**Comment by PRMerger10** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by BrianBlanchard — APPROVED** [review]

**Comment by PRMerger10** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrianBlanchard** [comment]
#sign-off

**Pull request merged**
