### PR TITLE
Contoso migration update2

### PR DESCRIPTION
**Pull request by deltadan**
Here is the final update from the Azure Migrate PM team. @alexbuckgit is onpoint for this PR.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @deltadan - Thanks for your pull request. A member of the content team will review it.

#hold-off Do not merge before PR review

**Comment by alexbuckgit** [comment]
@deltadan - Please revert the modifications that removed the comment directives for markdownlint, cSpell, and docsTest. We use these to automate a lot of quality checks for our content. Thanks!

**Comment by deltadan** [comment]
I have reverted that commit and pushed to the branch attached to this PR.

**Comment by ktoliver** [comment]
Hi @deltadan 

Would you remove these files from the pull request? The file types are not allowed in the content repository. Also, files can't be added to the root directory.

- .gitignore
- docs/migrate/azure-best-practices/media/contoso-migration-rds-to-wvd/.DS_Store

Thanks!

@tfosmark

**Comment by deltadan** [comment]
> Hi @deltadan
> 
> Would you remove these files from the pull request? The file types are not allowed in the content repository. Also, files can't be added to the root directory.
> 
> * .gitignore
> * docs/migrate/azure-best-practices/media/contoso-migration-rds-to-wvd/.DS_Store
> 
> Thanks!
> 
> @tfosmark

This has been completed.  There was a small change to one other doc based on PMM feedback.  We are ready to ship from our side.  Thanks!

**Comment by tfosmark** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@tfosmark: I'm sorry - only the author of this article, @deltadan, @benstegink, @givenscj, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by deltadan** [comment]
#sign-off

**Comment by PRMerger16** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Comment by ktoliver** [comment]
@alexbuckgit - _If you sign off_, we'll merge the PR. Be aware that some work needs to be done before the content aligns with the [quality criteria](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master) that's listed in the Microsoft Docs contributor guide (an internal link). These new articles are not currently in a TOC, so you have a chance to do some clean-up before they are discoverable.

Here's what I see as needing to be fixed up (typically called **blocking** issues):

- All file names can contain only lowercase letters, numbers, and hyphens. Words must be separated by hyphens.
- Custom alert Markdown needs to be configured correctly.
- Image references need to be configured correctly.
- Images should be no more than 1200 pixels wide and should be enclosed in a light gray border that's 1 pixel wide. (It's nearly impossible to distinguish headings in screenshots from the page text in many of the images. Image relative size also varies widely.)
- Images should have clear resolution, are free of misspelled words, and contain no private information. All images must render and be legible in both light and dark views on the docs site. (I didn't check for these.)
- Lists of sequential steps should be numbered. 
- When there are numbered steps in headings, make sure all steps are configured the same (e.g., all H2s) and that they all appear in the on-page TOC.
- New articles must be added to a TOC.
- Only one H1 in an article--it's the article title.
- Remove "en-us" from docs.microsoft.com URLs.
- Change docs.microsoft.com//azure... to docs.microsoft.com/azure...
- Check all links. It looks like relative links to articles in the same folder are set up incorrectly.
- Lists and list items must be indented and aligned correctly.
- The metadata **title** attribute must be sentence case.
- The article title (H1) must be sentence case.
- Articles must contain an introductory paragraph. (You can't start off with a table right after the article title/H1.)
- Ensure that a branded product name is present in either the **title** or **titleSuffix** attribute. (I didn't check this.)
- All articles must have an Acrolinx score of 80 or above. No valid spelling errors or do-not-use technology in the Acrolinx reports. No blocking validation issues. (Can't check these in the public repository.)

Good things to look for and fix (typically called **nonblocking** issues):

- When referring to a company (Contoso), use "it" and "its" instead of "they" and "their".
- The header row in a list is automatically formatted as bold; no need to add bold Markdown to the items in the header.
- Use ending punctuation in lists.
- Use action verbs instead of gerunds in titles and headings ("Migrate" instead of "Migrating").
- Alt text should describe the image type, e.g., "Screenshot of the Configure virtual machines pane."; "Diagram of the migration architecture."
- Articles should have a "Next steps" section at the end with one to three relevant and compelling next steps. Brief text should be included that helps the customer understand why the next steps are relevant. 
- Conclusion sections are atypical in Microsoft Docs articles.
- The H2 headings, when rendered in the on-page TOC, should ideally wrap to no more than two lines. Longer headings make the article TOC harder to scan.
- All titles and headings should be sentence case, per MSFT style.
- An edit pass would be a great idea, so the content aligns with Microsoft style.

Thanks!

**Comment by alexbuckgit** [comment]
Moving to draft for review phase.

**Comment by alexbuckgit** [comment]
Updates incorporated via our private repo. Closing this PR.

**Pull request closed without merging**
