### PR TITLE
change name to AKS landing zone accelerator

### PR DESCRIPTION
**Pull request by mosabami**
Change the names from Enterprise scale for AKS to AKS landing zone accelerator

### CODE REVIEW

**Comment by PRMerger5** [comment]
@mosabami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@JanetCThomas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
#sing-off

**Comment by ktoliver** [comment]
🎵

**Pull request merged**
