### PR TITLE
Update resource-naming.md

### PR DESCRIPTION
**Pull request by jasonhorner**
Adding entry for azure analysis services

### CODE REVIEW

**Comment by PRMerger20** [comment]
@jasonhorner : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.

@MicrosoftDocs/public-repo-pr-review-team

**Comment by ShannonLeavitt** [comment]
#assign: @martinekuan
#unassign: @BrianBlanchard

**Comment by BryanLa** [comment]
#label:"cact-review-in-progress"

**Comment by BryanLa** [comment]
@jasonhorner - thanks for your contribution and apologies for the long delay..

CACT #sign-off
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Pull request merged**
