### PR TITLE
Updates revoke certificate error

### PR DESCRIPTION
**Pull request by omurthy**
I solved a problem by adding a config. So I added it to the documentation

### CODE REVIEW

**Comment by PRMerger10** [comment]
@omurthy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
@likamrat - can you please review and provide #sign-off?

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by likamrat** [comment]
#sign-off

**Pull request merged**
