### PR TITLE
New abbreviations

### PR DESCRIPTION
**Pull request by balazs92117**
New abbreviation recommendation for Recovery Services vault backup policy and Backup vault

### CODE REVIEW

**Comment by PRMerger8** [comment]
@balazs92117 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by JanetCThomas** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by GitHubber17** [comment]
The amount of changes in the PR changed as a result of resolving the merge conflict, and as a result, the CLA signature notification was added.

**Pull request merged**
