### PR TITLE
Update cloud-governance.md

### PR DESCRIPTION
**Pull request by frachkid**
I believe COBIT is a better example than ITIL when it comes to IT governance
http://www.isaca.org/COBIT/Pages/default.aspx

### CODE REVIEW

**Comment by PRMerger16** [comment]
@frachkid : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by frachkid** [comment]
I agree with that, probably removing all 3 (ITIL, ITSM & COBIT) is a better choice IMHO since I would like to avoid a discussion with the customer around frameworks all together and keep the narrative focused on Azure governance.

**Comment by ktoliver** [comment]
Hi @brianblanchard - Could you indicate how you'd like to proceed with the pull request? Thanks.

**Comment by BrianBlanchard** [comment]
@alexbuckgit, please ensure the short term approach taken here is consistent with other articles. 

Adding separate tasks to the backlog to test and take a holistic stance betting this article & PR.

**Comment by PRMerger9** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
