### PR TITLE
Added links to toolkits + added Error Analysis

### PR DESCRIPTION
**Pull request by omri374**
Solves #503 

Changes:
1. Added links to all libraries
2. Renamed white noise to Smart Noise
3. Added a reference to the Error Analysis toolkit
4. Minor rephrasing

### CODE REVIEW

**Comment by PRMerger17** [comment]
@omri374 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@v-hanki Could you review the proposed update? If it's approved, the locale `en-us` needs to be removed from azure.microsoft.com and docs.microsoft.com URLs before the PR is merged. Thanks.

**Comment by PRMerger14** [comment]
@omri374 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by WendyRing** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@WendyRing: I'm sorry - only the author of this article, @v-hanki, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
