### PR TITLE
Update ai-machine-learning-mlops.md

### PR DESCRIPTION
**Pull request by MG-Microsoft**
Adding Azure MLOps video series link as Dennis Eikelenboom suggested

### CODE REVIEW

**Comment by PRMerger10** [comment]
@MG-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@manu-kanwarpal Could you review the proposed changes to your article? Note that per the pull request quality criteria that's listed in the internal contributor guide, "External video links must go to Microsoft channels (that is, a Microsoft-sponsored channel on YouTube)." The links don't appear to go to Microsoft-sponsored channels.

**Comment by MG-Microsoft** [comment]
@manu-kanwarpal & @ktoliver I didnt have the permission to unload the videos in Microsoft channel so I created the channel and uploaded all there ( took me almost 1 week to upload as they are in 4k quality)

**Review by manu-kanwarpal — APPROVED** [review]

**Review by manu-kanwarpal — APPROVED** [review]

**Comment by ktoliver** [comment]
We'll send a business approval request to the content manager. Please stand by. Thanks.

**Pull request merged**
