### PR TITLE
Update migrate.md

### PR DESCRIPTION
**Pull request by dellis2121**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@dellis2121 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Matticusau - Would you review the proposed update to your article? Thanks.

**Comment by PRMerger19** [comment]
@JanetCThomas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
@Matticusau These look okay to me if you could sign off and merge the changes please.

**Review by Matticusau — APPROVED** [review]
Thanks LGTM

**Pull request merged**
