### PR TITLE
change the name from enterprise scale

### PR DESCRIPTION
**Pull request by mosabami**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@mosabami : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@mosabami: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by JanetCThomas** [comment]
@mosabami - is the date the only change?

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by JanetCThomas** [comment]
#sign-off  the only change is the date. this has been reviewed by the content team.

**Comment by PRMerger12** [comment]
@JanetCThomas: I'm sorry - only the author of this article, @BrianBlanchard, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
