### PR TITLE
add security drivers

### PR DESCRIPTION
**Pull request by MarkSimos**
merged two bullets and added a new one on modernizing security platform

### CODE REVIEW

**Comment by PRMerger20** [comment]
@MarkSimos : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Resolved the merge conflict.

@brianblanchard - Could you review the proposed changes? Thanks.

**Comment by PRMerger10** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
