### PR TITLE
Update scale-architectures.md

### PR DESCRIPTION
**Pull request by felixzieger**

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[d306bad](https://github.com/felixzieger/cloud-adoption-framework/commits/d306bad90c4d088b998696bb0370af206255acfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/cloud-scale-analytics/architectures/scale-architectures.md](https://github.com/felixzieger/cloud-adoption-framework/blob/patch-1/docs/scenarios/cloud-scale-analytics/architectures/scale-architectures.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202212020840114682-1017/BuildReport?accessString=c701535223dbc6b1be03804ed1456f81384b47a4fe0edd3201a92fec4c8f21b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@marvinbuss

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ckittel — APPROVED** [review]
Thanks for the typo fix!

**Comment by ckittel** [comment]
#sign-off

**Pull request merged**
