### PR TITLE
Update Enterprise-scale to LandingZone Accelerator

### PR DESCRIPTION
**Pull request by sblair01**
Changing to match nav and consistency with the rest of the Azure docs.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@sblair01 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @pgandham

**Comment by Court72** [comment]
@alexbuckgit 

GitHub doesn't recognize the `author` listed in the metadata. I see you've made recent updates to the article. Can you review the proposed changes?

 *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by Court72** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, add a sign-off.
	
#label:"aq-pr-triaged"
#label:"pending-content-team/business-approval"
Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
CACT #sign-off
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Comment by ShannonLeavitt** [comment]
I'm merging per @BryanLa sign-off. But note that the document title no longer matchs the description or the H1 heading. 

image

**Comment by BryanLa** [comment]
@ShannonLeavitt - thanks for pointing that out. Unfortunately it's even different than that if you look at the 'main' branch (as that commit screenshot for this PR is even older). I'll file another PR to reconcile the metadata and H1..
image

**Pull request merged**
