### PR TITLE
Update tools-templates.md

### PR DESCRIPTION
**Pull request by janicericketts**
Removed graphic per PR 3610 request @ShannonLeavitt

### CODE REVIEW

**Comment by PRMerger10** [comment]
@janicericketts : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by janicericketts** [comment]
#sign-off

**Comment by PRMerger15** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @JanetCThomas

**Comment by JanetCThomas** [comment]
#sign-off

**Pull request merged**
