### PR TITLE
ANF updates

### PR DESCRIPTION
**Pull request by arntdg**
Removed "third-party" in front of ANF and added link to ANF for Kubernetes workloads

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[1d2496b](https://github.com/arntdg/cloud-adoption-framework/commits/1d2496b1a4ff3adc256f2a115c583fefd96d192c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/app-platform/aks/storage.md](https://github.com/arntdg/cloud-adoption-framework/blob/patch-3/docs/scenarios/app-platform/aks/storage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202210060904307361-965/BuildReport?accessString=ecb7ea4d01186ad633f62f451f7a3a8da1f9254bef34c962997c6eb3ec2654fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@gbowerman 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by gbowerman** [comment]
@Court72 owner to sign off on this should be @mosabami

**Comment by gbowerman** [comment]
#sign-off

**Comment by jborsecnik** [comment]
Due to the upcoming Ignite conference, all merging and publishing is on hold until the morning of October 12.

This PR is ready for merge on 10/12.

**Comment by Court72** [comment]
> @Court72 owner to sign off on this should be @mosabami

@gbowerman 

Thanks! Can you open a PR in the private repo to update the author metadata?

image

**Pull request merged**
