### PR TITLE
Update cloud-adoption.md

### PR DESCRIPTION
**Pull request by wayneme75**
adding a paragraph around the inclusion of automation in the early phases.. not necessarily building out the full automation function but starting to think about it.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@wayneme75 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrianBlanchard** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@BrianBlanchard: I'm sorry - only the author of this article, @JanetCThomas, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
