### PR TITLE
Update network-topology-and-connectivity.md

### PR DESCRIPTION
**Pull request by asukumar22**
Added WAF to app gateway use case/choice

In the following lines, WAF capabilities are not mentioned for Application gateway for regional load balancing needs.

Connecting to an App Service:
  - Ensure you have a [Web Application Firewall](/azure/web-application-firewall/overview) (WAF) implemented in front of your App Service, using [Azure Front Door](/azure/web-application-firewall/afds/afds-overview), [Azure Application Gateway](/azure/web-application-firewall/ag/ag-overview), or a third-party service, to provide OWASP-based protection. You can use either Front Door or App Gateway for a single region, or both if you're doing multi-region. If you need path routing within the region, you would need App Gateway, and if you need multi-region load balancing and WAF, you would need Front Door.

Changed in Line 51: If you need path routing and WAF within the region, you would need App Gateway, and if you need multi-region load balancing and WAF, you would need Front Door.

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[90746db](https://github.com/asukumar22/cloud-adoption-framework/commits/90746db2927a61f0d26d549a2de566cd1e10f2fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/app-platform/app-services/network-topology-and-connectivity.md](https://github.com/asukumar22/cloud-adoption-framework/blob/patch-1/docs/scenarios/app-platform/app-services/network-topology-and-connectivity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202212212152501288-1034/BuildReport?accessString=e09b0246a9a25f67bc7a9ebd96befab536e58e7f97741037187f1b71c2786a2f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Jak-MS** [comment]
@martinekuan 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by martinekuan** [comment]
#sign-off

**Comment by Court72** [comment]
After resolving the merge conflict, it appears changes have already been made to the article, so we'll close this PR.

If you see that the issue isn't resolved, please open a new PR. Thanks!

**Pull request closed without merging**
