### PR TITLE
Updated doc & included Naming Tool

### PR DESCRIPTION
**Pull request by shbabylo**
Have broken out the document a bit more to make it easier to digest, incorporated references to highlight these are examples only, added CAF tools references for quick access, and cleaned up charts both in providing standard and to reduce examples vs trying to include all naming resources.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@shbabylo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by JanetCThomas** [comment]
@dominicallen - This looks solid can we merge it.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@JanetCThomas I'm working to resolve merge conflicts. I need to check the update against what's in master one more time, and then I will merge.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I'll merge the PR now. Substantial updates had been made in master in the private repo, resulting in substantial merge conflicts. I would recommend a careful review after the public and private repos sync, to be sure that the version you end up with in master in the private repo is the version you want in all sections.

**Comment by PRMerger4** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
