### PR TITLE
Update network-topology-and-connectivity.md

### PR DESCRIPTION
**Pull request by asukumar22**
Added - Access Restrictions as a bulleted point in Line 25.

In Line 64, - If you need a dedicated outbound address when connecting to a multi-tenanted App Service, use a [NAT Gateway](/azure/app-service/networking/nat-gateway-integration). , pls change the dedicated outbound IP address to the Outbound Public IP address.

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[7a50af9](https://github.com/asukumar22/cloud-adoption-framework/commits/7a50af9be1f8661fb4b858476d251755a0423851)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenarios/app-platform/app-services/network-topology-and-connectivity.md](https://github.com/asukumar22/cloud-adoption-framework/blob/patch-2/docs/scenarios/app-platform/app-services/network-topology-and-connectivity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/0286ad65-6ec8-0c70-0cae-2edc1504c701/202212212202330658-1035/BuildReport?accessString=f4956c430bf37589a146e9c5b57dd18713978f2d7fc585ea6b8e3c200862dc5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0286ad65-6ec8-0c70-0cae-2edc1504c701?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Jak-MS** [comment]
@martinekuan 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by martinekuan** [comment]
#sign-off

**Comment by Court72** [comment]
This [article has been edited](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/app-services/network-topology-and-connectivity.md) since the time this PR was opened, and these changes no longer apply. We'll close this PR. Thanks!

**Pull request closed without merging**
